#!/bin/bash

HOST=your_server_name

if [ "$#" != 1 ] ; then
	echo "Usage:   $0 PORT_NUMBER"
	echo "Example: $0 8080"
	exit 1
fi

set -e


KEYFILE=`mktemp`
cat > "$KEYFILE" <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
your_private_key_ssh
-----END OPENSSH PRIVATE KEY-----
EOF

socket=/tmp/webrelay-`cat /dev/urandom | LC_CTYPE=C tr -dc A-Za-z0-9 | fold -w 20 | head -n 1`.socket

ssh -o ServerAliveInterval=5 -o ServerAliveCountMax=1 -i "$KEYFILE" -T -x -R "$socket:127.0.0.1:$1" "$HOST" "$socket $1"

rm "$KEYFILE"

